spring:
  datasource:
    username: root
    password: root@123
    url: jdbc:mysql://localhost:3306/self?useUnicode=true&characterEncoding=utf-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiaojun.self.po

server:
  port: 8070

swaggerUrl:
  driftingjane.s1.natapp.cc